version: '3.9'

services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
      - MONGO_INITDB_DATABASE=mongodb
      - MONGO_NON_ROOT_USERNAME=user
      - MONGO_NON_ROOT_PASSWORD=user

  mongo-seed:
    build: migration
    depends_on:
      - mongodb
    links:
      - mongodb

#  user-application:
#    build: .
#    ports:
#      - 8081:8081
#    depends_on:
#      - mongodb
#    links:
#      - mongodb