apiVersion: v2
name: application
description: A Helm chart to deploy Application in Kubernetes
# chart type
type: application
# chart version
version: 0.2.1
# cinema app version
appVersion: "v2.1.2"
dependencies:
  - condition: mongodb.enabled
    name: mongodb
    repository: https://charts.bitnami.com/bitnami
    version: 10.4.0
  - name: users
    version: 0.2.x
